name: Test Optimizely Flags Notifier Action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Action
        uses: hitarthdesai/optimizely-flags-notifier@v0.2.0
        with:
          optimizely_project_id: ${{ secrets.OPTIMIZELY_PROJECT_ID }}
          optimizely_auth_token: ${{ secrets.OPTIMIZELY_API_KEY }}
          slack_app_bot_token: ${{ secrets.SLACK_USERNAME }}
          channel_id: ${{ secrets.CHANNEL_ID }}
